name = "matroid-test-lean"
version = "0.1.0"
defaultTargets = ["Matroid"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc3"

[[lean_lib]]
name = "Matroid"
roots = ["Matroid.Matroid", "Matroid.Internal.Basic", "Matroid.Internal.Frontier2"]
